spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
#    &allowPublicKeyRetrieval=true
    url: 'jdbc:mysql://127.0.0.1:3306/snowflakes?userUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8'
    username: snowflakes
    password: snowflakes
    
